BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[sysDept] ALTER COLUMN [Divs_id] CHAR(10) NULL;
ALTER TABLE [dbo].[sysDept] ALTER COLUMN [name] VARCHAR(100) NULL;
ALTER TABLE [dbo].[sysDept] ALTER COLUMN [createdBy] CHAR(10) NULL;
ALTER TABLE [dbo].[sysDept] ALTER COLUMN [createdAt] DATETIME2 NULL;
ALTER TABLE [dbo].[sysDept] ALTER COLUMN [updatedBy] CHAR(10) NULL;
ALTER TABLE [dbo].[sysDept] ALTER COLUMN [branch_id] CHAR(10) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
