BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[hosAdmission] ALTER COLUMN [patientCase] VARCHAR(2550) NOT NULL;

-- AlterTable
ALTER TABLE [dbo].[hosPatientReferred] ALTER COLUMN [referredCase] VARCHAR(250) NOT NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
