BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[User] ADD CONSTRAINT [User_createdAt_df] DEFAULT CURRENT_TIMESTAMP FOR [createdAt], CONSTRAINT [User_updatedAt_df] DEFAULT CURRENT_TIMESTAMP FOR [updatedAt];

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
